Add .tool-versions and read java version for version-update.yml from it.
Also added a note in the version catalog to remember to update both together.

diff --git a/.github/workflows/version-update.yml b/.github/workflows/version-update.yml
--- a/.github/workflows/version-update.yml
+++ b/.github/workflows/version-update.yml
@@ -16,11 +16,28 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
 
-# TODO: Read Java version from .tools-version
+      - name: Establish library build Java version
+        id: establish_java_for_library_build
+        run: |
+          if [ ! -f .tool-versions ]; then
+            echo "::error title=Missing .tool-versions file::gha-gradle-library-release-workflow requires an asdf-format .tool-versions file to establish the Java version for the build."
+            exit 1
+          fi
+          LIBRARY_BUILD_MAJOR_JAVA_VERSION=$( grep -Eo 'java [[:alnum:]-]+-[[:digit:]]+' .tool-versions | rev | cut -d'-' -f1 | rev )
+          echo "Using Java $LIBRARY_BUILD_MAJOR_JAVA_VERSION"
+          if [ -z "${LIBRARY_BUILD_MAJOR_JAVA_VERSION}" ]; then
+            echo "::error title=Missing Java version in .tool-versions file::Could not establish the library's required Java version - the '.tool-versions' file should have a line like 'java corretto-21.0.3.9.1'."
+            exit 1
+          fi
+          
+          cat << EndOfFile >> $GITHUB_OUTPUT
+          library_build_major_java_version=$LIBRARY_BUILD_MAJOR_JAVA_VERSION
+          EndOfFile
+
       - name: Set up JDK 17
         uses: actions/setup-java@v4
         with:
-          java-version: '17'
+          java-version: ${{ steps.establish_java_for_library_build.outputs.library_build_major_java_version }}
           distribution: 'temurin'
 
       - name: Setup Gradle
